SQLALCHEMY_DATABASE_URI = 'mysql://nestegg:nestegg@localhost/nestegg'
SQLALCHEMY_ECHO = True

RECAPTCHA_PUBLIC_KEY = '6LfrqAETAAAAAO_BbffXgjLZJ_iEOHNgGBy5Jo2z'
RECAPTCHA_PRIVATE_KEY = '6LfrqAETAAAAABe7HiBUZAMy9M-lp7kunMwp42eB'